/* eslint-disable consistent-return */
/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import { ViewGridIcon, MicrophoneIcon } from '@heroicons/react/solid/';
import { SearchIcon } from '@heroicons/react/outline';
import Image from 'next/image';
import { useRef } from 'react';
import { useRouter } from 'next/router';
import Avatar from '../components/Avatar';
import Footer from '../components/Footer';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return null;

    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className=" flex w-full p-5 justify-between text-sm text-gray-700 font-medium">
        {/* Left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          {/* Avatar */}
          <Avatar url="/user.jpeg" />
        </div>
      </header>

      {/* Body */}
      <form
        className="flex flex-col items-center mt-44 flex-grow w-4/5"
        onSubmit={search}
      >
        {/* Google Logo */}
        <Image
          src="/google.svg"
          width={300}
          height={100}
        />
        {/* Input Container */}
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200
        px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl xl:max-w-3xl "
        >
          <SearchIcon className="h-5 mr-3 text-gray-500 rounded-full hover:bg-gray-100 cursor-pointer" />

          <input
            type="text"
            className="focus:outline-none flex-grow"
            ref={searchInputRef}
          />

          <MicrophoneIcon className="h-5 text-gray-700 rounded-full hover:bg-gray-100 cursor-pointer" />
        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} type="button" className="btn">
            Google Search
          </button>
          <button onClick={search} type="button" className="btn">
            I'm feeling Lucky
          </button>
        </div>
      </form>
      {/* Footer */}
      <Footer />
    </div>
  );
}
